#!/usr/bin/bash

# cmd = 'gsettings set org.gnome.desktop.session idle-delay %d'

usage() {
    echo "Usage: $0 DURATION<suffix>"
    echo "suffix can be s/m/h for minutes/hours, if no suffix is \
provided seconds is used by default"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

DURATION=$1

if echo $DURATION | egrep "[0-9]+$" > /dev/null; then
    # If no suffix, default is seconds
    seconds=$DURATION
    intervl=$DURATION
    unit="seconds"
elif echo $DURATION | egrep -i "[0-9]+[sS]$" >/dev/null; then
    seconds=`echo $DURATION | sed "s/[sS]//g"`
    intervl=$seconds
    unit="seconds"
elif echo $DURATION | egrep -i "[0-9]+[mM]$" >/dev/null; then
    intervl=`echo $DURATION | sed "s/[mM]//g"`
    seconds=`echo "$intervl * 60" | bc -q`
    unit="minutes"
elif echo $DURATION | egrep -i "[0-9]+[hH]$" >/dev/null; then
    intervl=`echo $DURATION | sed "s/[hH]//g"`
    seconds=`echo "$intervl * 60*60" | bc -q`
    unit="hours"
else
    usage
fi

if [ $intervl = 0 ]; then
     echo "Disabling screen lock..."
else
     echo "Setting screen lock to $intervl $unit..."
fi

gsettings set org.gnome.desktop.session idle-delay $seconds
