#!/usr/bin/python3

# sstring: print the names of the six strings of a guitar randomly by
# default.

from argparse import ArgumentParser
from random import randrange
from time import sleep
from os import system, get_terminal_size

# Defaults
duration = 4
random = True
columns = get_terminal_size().columns
rows = int((get_terminal_size().lines-6)/2)

# GNOME screen autolock disable
# Set 0 to disable and 300 for 5 minutes
# Thanks to:
# https://askubuntu.com/questions/177348/how-do-i-disable-the-screensaver-lock
cmd="gsettings set org.gnome.desktop.session idle-delay 0"
system(cmd)

def printstr(string):
    system("clear")
    print("\n"*rows)
    print(string.center(columns), flush=True)

parser = ArgumentParser()
parser.add_argument("-s", "--seq", action="store_true",
                    help="Print string names sequentially "
                    "(Default is random)")
parser.add_argument("-p", "--pairs", action="store_true",
                    help="Print string names in pairs")
parser.add_argument("-l", "--triplets", action="store_true",
                    help="Print string names in triples")
parser.add_argument("-t", "--time", help="interval in seconds "
                    "(default: 4s)", type=int)
parser.add_argument("-b", "--reverse", action="store_true",
                    help="Print string names backwards")
args = parser.parse_args()


if args.time:
    duration = args.time
if args.seq:
    random = False
pairs = args.pairs
triplets = args.triplets

strings = [ 'E', 'A', 'D', 'G', 'B', 'e' ]
pairstrings = [ "E\te", "A\tB", "D\tG" ]
triples = [ "E   A   D", "G   B   e" ]

try:
    while True:
        if random:
            if pairs:
                printstr(pairstrings[randrange(0, 3)])
            elif triplets:
                printstr(triples[randrange(0, 2)])
            else:
                printstr(strings[randrange(0, 6)])
            sleep(duration)
        else:
            if args.reverse:
                if pairs:
                    for i in range(2, -1, -1):
                        printstr(pairstrings[i])
                        sleep(duration)
                elif triplets:
                    for i in range(1, -1, -1):
                        printstr(triples[i])
                        sleep(duration)
                else:
                    for i in range(5, -1, -1):
                        printstr(strings[i])
                        sleep(duration)
            else:
                if pairs:
                    for i in range(0, 3):
                        printstr(pairstrings[i])
                        sleep(duration)
                elif triplets:
                    for i in range(0, 2):
                        printstr(triples[i])
                        sleep(duration)
                else:
                    for i in range(0, 6):
                        printstr(strings[i])
                        sleep(duration)
except KeyboardInterrupt:
    cmd="gsettings set org.gnome.desktop.session idle-delay 300"
    system(cmd)
